const seedGrid=document.getElementById('seedGrid'),searchInput=document.getElementById('searchInput'),categoryFilter=document.getElementById('categoryFilter'),seedSelect=document.getElementById('seedSelect'),seedCount=document.getElementById('seedCount'),settingsToggle=document.getElementById('settingsToggle'),accessMenu=document.getElementById('accessMenu'),themeToggle=document.getElementById('themeToggle'),fontInc=document.getElementById('fontInc'),fontDec=document.getElementById('fontDec'),speakBtn=document.getElementById('speakBtn'),stopSpeakBtn=document.getElementById('stopSpeakBtn'),dialog=document.getElementById('seedDialog'),closeDialog=document.getElementById('closeDialog'),dialogContent=document.getElementById('dialogContent'),logForm=document.getElementById('logForm'),logTableBody=document.getElementById('logTableBody'),exportBtn=document.getElementById('exportBtn'),clearBtn=document.getElementById('clearBtn'),LS_THEME='seedbank_theme',LS_SCALE='seedbank_scale',LS_LOGS='seedbank_logs';
function applyTheme(t){document.documentElement.setAttribute('data-theme',t);localStorage.setItem(LS_THEME,t)}
function applyScale(s){const n=Math.min(1.35,Math.max(.9,Number(s)));document.documentElement.style.setProperty('--font-scale',n);localStorage.setItem(LS_SCALE,n)}
function closeAccessMenu(){settingsToggle.setAttribute('aria-expanded','false');accessMenu.hidden=true}
function toggleAccessMenu(force){const open=typeof force==='boolean'?force:settingsToggle.getAttribute('aria-expanded')!=='true';settingsToggle.setAttribute('aria-expanded',String(open));accessMenu.hidden=!open}
applyTheme(localStorage.getItem(LS_THEME)||'dark');
applyScale(localStorage.getItem(LS_SCALE)||1);
settingsToggle.addEventListener('click',e=>{e.stopPropagation();toggleAccessMenu()});
accessMenu.addEventListener('click',e=>e.stopPropagation());
document.addEventListener('click',e=>{if(!e.target.closest('.settings-wrap'))closeAccessMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAccessMenu()});
function runAndClose(fn){return ()=>{fn();closeAccessMenu()}}
themeToggle.addEventListener('click',runAndClose(()=>applyTheme(document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark')));
fontInc.addEventListener('click',runAndClose(()=>applyScale((parseFloat(localStorage.getItem(LS_SCALE)||1)+.05).toFixed(2))));
fontDec.addEventListener('click',runAndClose(()=>applyScale((parseFloat(localStorage.getItem(LS_SCALE)||1)-.05).toFixed(2))));
speakBtn.addEventListener('click',runAndClose(()=>{window.speechSynthesis.cancel();const txt=document.body.innerText.slice(0,4000);const u=new SpeechSynthesisUtterance(txt);u.lang='es-CL';window.speechSynthesis.speak(u)}));
stopSpeakBtn.addEventListener('click',runAndClose(()=>window.speechSynthesis.cancel()));
function uniqueCategories(){return [...new Set(window.SEED_DATA.map(s=>s.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function fillFilters(){uniqueCategories().forEach(cat=>{const opt=document.createElement('option');opt.value=cat;opt.textContent=cat;categoryFilter.appendChild(opt)})}
function fillSeedSelect(){seedSelect.innerHTML='<option value="">Seleccionar...</option>';window.SEED_DATA.forEach(seed=>{const opt=document.createElement('option');opt.value=seed.id;opt.textContent=seed.name;seedSelect.appendChild(opt)})}
function getSeedDescription(seed){return seed.description||`Semilla de ${seed.name} orientada a trabajo escolar en invernadero. Permite registrar ${seed.researchFocus.slice(0,3).join(', ')} y comparar resultados por equipo.`}
function cardTemplate(seed){return `<article class="seed-card"><button data-seed-id="${seed.id}"><img src="${seed.frontImage}" alt="${seed.name}"><div class="seed-body"><h3>${seed.name}</h3><p class="seed-desc">${getSeedDescription(seed)}</p><div class="badge-row"><span class="badge">${seed.category||'Por clasificar'}</span><span class="badge">${seed.season||'Sin temporada'}</span></div><div class="meta"><span><strong>Especie:</strong> ${seed.scientificName||'Pendiente de completar'}</span><span><strong>Dificultad:</strong> ${seed.difficulty}</span><span><strong>Enfoque:</strong> ${seed.researchFocus.slice(0,2).join(', ')}</span></div></div></button></article>`}
function renderSeeds(){const term=searchInput.value.trim().toLowerCase(),filter=categoryFilter.value,filtered=window.SEED_DATA.filter(seed=>{const haystack=[seed.name,seed.category,seed.scientificName,seed.description,...(seed.researchFocus||[])].join(' ').toLowerCase();return (!term||haystack.includes(term))&&(!filter||seed.category===filter)});seedGrid.innerHTML=filtered.map(cardTemplate).join('');document.querySelectorAll('.seed-card button').forEach(btn=>btn.addEventListener('click',()=>openSeedDialog(btn.dataset.seedId)));seedCount.textContent=window.SEED_DATA.length}
function openSeedDialog(id){const seed=window.SEED_DATA.find(s=>s.id===id);if(!seed)return;dialogContent.innerHTML=`<div class="dialog-layout"><div class="dialog-images"><figure><img src="${seed.frontImage}" alt="Vista frontal del sobre ${seed.name}"><figcaption>Frontal del sobre</figcaption></figure><figure><img src="${seed.backImage||seed.frontImage}" alt="Vista posterior del sobre ${seed.name}"><figcaption>Reverso del sobre</figcaption></figure></div><div class="dialog-info"><span class="eyebrow">Ficha pedagógica</span><h3>${seed.name}</h3><p class="dialog-desc">${getSeedDescription(seed)}</p><p><strong>Nombre científico:</strong> ${seed.scientificName||'Pendiente de completar'}</p><p><strong>Categoría:</strong> ${seed.category}</p><p><strong>Temporada sugerida:</strong> ${seed.season||'No registrada'}</p><p><strong>Días de germinación:</strong> ${seed.daysGermination||'Completar según el sobre'}</p><p><strong>Días a cosecha:</strong> ${seed.daysHarvest||'Completar según el sobre'}</p><p><strong>Nota:</strong> ${seed.notes}</p><h4>Ideas de investigación</h4><ul>${seed.researchFocus.map(i=>`<li>${i}</li>`).join('')}</ul></div></div>`;dialog.showModal()}
closeDialog.addEventListener('click',()=>dialog.close());
searchInput.addEventListener('input',renderSeeds);
categoryFilter.addEventListener('change',renderSeeds);
function getLogs(){return JSON.parse(localStorage.getItem(LS_LOGS)||'[]')}
function saveLogs(logs){localStorage.setItem(LS_LOGS,JSON.stringify(logs))}
function renderLogs(){const logs=getLogs().sort((a,b)=>(b.date||'').localeCompare(a.date||''));logTableBody.innerHTML=logs.map(log=>`<tr><td>${log.date}</td><td>${log.seedName}</td><td>${log.team}</td><td>${log.stage}</td><td>${log.height||'—'} cm</td><td>${log.leaves||'—'}</td><td>${log.obs||'—'}</td></tr>`).join('')}
logForm.addEventListener('submit',e=>{e.preventDefault();const seed=window.SEED_DATA.find(s=>s.id===seedSelect.value);if(!seed)return;const entry={date:document.getElementById('dateInput').value,seedId:seed.id,seedName:seed.name,team:document.getElementById('teamInput').value.trim(),stage:document.getElementById('stageInput').value,height:document.getElementById('heightInput').value,leaves:document.getElementById('leavesInput').value,obs:document.getElementById('obsInput').value.trim()};const logs=getLogs();logs.push(entry);saveLogs(logs);renderLogs();logForm.reset();document.getElementById('dateInput').valueAsDate=new Date()});
exportBtn.addEventListener('click',()=>{const logs=getLogs();if(!logs.length){alert('No hay registros para exportar.');return}const headers=['fecha','semilla','equipo','etapa','altura_cm','hojas','observacion'],rows=logs.map(l=>[l.date,l.seedName,l.team,l.stage,l.height,l.leaves,(l.obs||'').replaceAll('"','""')]),csv=[headers.join(','),...rows.map(r=>r.map(v=>`"${v??''}"`).join(','))].join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bitacora_semillas.csv';a.click();URL.revokeObjectURL(a.href)});
clearBtn.addEventListener('click',()=>{if(!confirm('¿Seguro que deseas eliminar todos los registros guardados en este navegador?'))return;localStorage.removeItem(LS_LOGS);renderLogs()});
fillFilters();fillSeedSelect();renderSeeds();renderLogs();document.getElementById('dateInput').valueAsDate=new Date();